nome = input('Digite seu nome: ')
print('Seja bem vindo, ',nome)
dia = input('Digite o dia do seu aniversário: ')
mes = input('Digite o mês do seu aniversário: ')
ano = input('Digite o ano do seu aniversário: ')
print('Então', nome,',você nasceu no dia', dia, 'do', mes, 'no ano de', ano, '.Certo?')
